### ISSUE TITLE
View pre-retcon pages not working

### ISSUE THREAD

**Issue by rufioh** [madman-bob/Homestuck-POV-Cam#5]
So this list of links to pages with oil stain retcons still exists http://www.mspaintadventures.com/oilretcon.html  
Anyway, when I visit a page with an oilstain (i followed a link to page 3439 and it redirects you to 1539 on the new website), like https://www.homestuck.com/story/1539, even though I have "View pre-retcon pages (changes back on hover)" enabled, it doesn't actually show me the pre-retcon pages.  
  
The pre-retcon files do still exist though, see: https://www.homestuck.com/images/storyfiles/hs2/01539_retcon.gif 
and
https://www.homestuck.com/images/storyfiles/hs2/01539.gif

The view pre-retcon image still seems to work if you access the old mspa site like this http://www.mspaintadventures.com/test_index.php?s=6&p=003439

**Comment by madman-bob** [comment]
Looks ok to me. Does it still happen for you? If so, do you have any other extensions installed?

**Comment by rufioh** [comment]
I tried it on a fresh version of chrome and I get the same issue. The only extension installed is this one. I've taken some screen shots and put them on an imgur album with "elements" visible https://imgur.com/a/f2il5fK

**Comment by madman-bob** [comment]
Ah, a fresh install did it for me. I'd made an assumption that's no longer true on the new site.

Fixed in https://github.com/madman-bob/Homestuck-POV-Cam/commit/e18b09f2fa20d9682f045adca5e24773653b642f, released in version 3.23
