### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by Sixthhokage1** [madman-bob/Homestuck-POV-Cam#6]
I was in the middle of working on porting this extension to a Firefox webextension when I noticed there was no license file. Just curious if this is intentionally keeping rights reserved or just an oversight

**Comment by madman-bob** [comment]
Added (5da6a7c674ffd3460612e04c4295dce731fbc51a).

Fair warning - this was my first semi-serious project, so some of the code may be a bit icky, but feel free to make whatever you can from it.
